// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseTaskDetail.proto

package com.xinguang.tubobo.msgprotocol.transfer;

public final class ResponseTaskDetailPB {
  private ResponseTaskDetailPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseTaskDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseTaskDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string taskNo = 1;</code>
     */
    java.lang.String getTaskNo();
    /**
     * <code>string taskNo = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskNoBytes();

    /**
     * <code>string senderAddress = 2;</code>
     */
    java.lang.String getSenderAddress();
    /**
     * <code>string senderAddress = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderAddressBytes();

    /**
     * <code>float senderDistance = 3;</code>
     */
    float getSenderDistance();

    /**
     * <code>float senderLatitude = 4;</code>
     */
    float getSenderLatitude();

    /**
     * <code>float senderLongitude = 5;</code>
     */
    float getSenderLongitude();

    /**
     * <code>string senderPhone = 6;</code>
     */
    java.lang.String getSenderPhone();
    /**
     * <code>string senderPhone = 6;</code>
     */
    com.google.protobuf.ByteString
        getSenderPhoneBytes();

    /**
     * <code>string senderName = 7;</code>
     */
    java.lang.String getSenderName();
    /**
     * <code>string senderName = 7;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>string receiverAddress = 8;</code>
     */
    java.lang.String getReceiverAddress();
    /**
     * <code>string receiverAddress = 8;</code>
     */
    com.google.protobuf.ByteString
        getReceiverAddressBytes();

    /**
     * <code>float receiverDistance = 9;</code>
     */
    float getReceiverDistance();

    /**
     * <code>float receiverLatitude = 10;</code>
     */
    float getReceiverLatitude();

    /**
     * <code>float receiverLongitude = 11;</code>
     */
    float getReceiverLongitude();

    /**
     * <code>string receiverName = 12;</code>
     */
    java.lang.String getReceiverName();
    /**
     * <code>string receiverName = 12;</code>
     */
    com.google.protobuf.ByteString
        getReceiverNameBytes();

    /**
     * <code>string receiverPhone = 13;</code>
     */
    java.lang.String getReceiverPhone();
    /**
     * <code>string receiverPhone = 13;</code>
     */
    com.google.protobuf.ByteString
        getReceiverPhoneBytes();

    /**
     * <code>string goodsType = 14;</code>
     */
    java.lang.String getGoodsType();
    /**
     * <code>string goodsType = 14;</code>
     */
    com.google.protobuf.ByteString
        getGoodsTypeBytes();

    /**
     * <code>float income = 15;</code>
     */
    float getIncome();

    /**
     * <code>float deliveryFee = 16;</code>
     */
    float getDeliveryFee();

    /**
     * <code>float tipFee = 17;</code>
     */
    float getTipFee();
  }
  /**
   * Protobuf type {@code ResponseTaskDetail}
   */
  public  static final class ResponseTaskDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseTaskDetail)
      ResponseTaskDetailOrBuilder {
    // Use ResponseTaskDetail.newBuilder() to construct.
    private ResponseTaskDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseTaskDetail() {
      taskNo_ = "";
      senderAddress_ = "";
      senderDistance_ = 0F;
      senderLatitude_ = 0F;
      senderLongitude_ = 0F;
      senderPhone_ = "";
      senderName_ = "";
      receiverAddress_ = "";
      receiverDistance_ = 0F;
      receiverLatitude_ = 0F;
      receiverLongitude_ = 0F;
      receiverName_ = "";
      receiverPhone_ = "";
      goodsType_ = "";
      income_ = 0F;
      deliveryFee_ = 0F;
      tipFee_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseTaskDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskNo_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              senderAddress_ = s;
              break;
            }
            case 29: {

              senderDistance_ = input.readFloat();
              break;
            }
            case 37: {

              senderLatitude_ = input.readFloat();
              break;
            }
            case 45: {

              senderLongitude_ = input.readFloat();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              senderPhone_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverAddress_ = s;
              break;
            }
            case 77: {

              receiverDistance_ = input.readFloat();
              break;
            }
            case 85: {

              receiverLatitude_ = input.readFloat();
              break;
            }
            case 93: {

              receiverLongitude_ = input.readFloat();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverName_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              receiverPhone_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              goodsType_ = s;
              break;
            }
            case 125: {

              income_ = input.readFloat();
              break;
            }
            case 133: {

              deliveryFee_ = input.readFloat();
              break;
            }
            case 141: {

              tipFee_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.internal_static_ResponseTaskDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.internal_static_ResponseTaskDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail.class, com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail.Builder.class);
    }

    public static final int TASKNO_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskNo_;
    /**
     * <code>string taskNo = 1;</code>
     */
    public java.lang.String getTaskNo() {
      java.lang.Object ref = taskNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskNo_ = s;
        return s;
      }
    }
    /**
     * <code>string taskNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskNoBytes() {
      java.lang.Object ref = taskNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderAddress_;
    /**
     * <code>string senderAddress = 2;</code>
     */
    public java.lang.String getSenderAddress() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string senderAddress = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderAddressBytes() {
      java.lang.Object ref = senderAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERDISTANCE_FIELD_NUMBER = 3;
    private float senderDistance_;
    /**
     * <code>float senderDistance = 3;</code>
     */
    public float getSenderDistance() {
      return senderDistance_;
    }

    public static final int SENDERLATITUDE_FIELD_NUMBER = 4;
    private float senderLatitude_;
    /**
     * <code>float senderLatitude = 4;</code>
     */
    public float getSenderLatitude() {
      return senderLatitude_;
    }

    public static final int SENDERLONGITUDE_FIELD_NUMBER = 5;
    private float senderLongitude_;
    /**
     * <code>float senderLongitude = 5;</code>
     */
    public float getSenderLongitude() {
      return senderLongitude_;
    }

    public static final int SENDERPHONE_FIELD_NUMBER = 6;
    private volatile java.lang.Object senderPhone_;
    /**
     * <code>string senderPhone = 6;</code>
     */
    public java.lang.String getSenderPhone() {
      java.lang.Object ref = senderPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderPhone_ = s;
        return s;
      }
    }
    /**
     * <code>string senderPhone = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSenderPhoneBytes() {
      java.lang.Object ref = senderPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object senderName_;
    /**
     * <code>string senderName = 7;</code>
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <code>string senderName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERADDRESS_FIELD_NUMBER = 8;
    private volatile java.lang.Object receiverAddress_;
    /**
     * <code>string receiverAddress = 8;</code>
     */
    public java.lang.String getReceiverAddress() {
      java.lang.Object ref = receiverAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverAddress = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverAddressBytes() {
      java.lang.Object ref = receiverAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERDISTANCE_FIELD_NUMBER = 9;
    private float receiverDistance_;
    /**
     * <code>float receiverDistance = 9;</code>
     */
    public float getReceiverDistance() {
      return receiverDistance_;
    }

    public static final int RECEIVERLATITUDE_FIELD_NUMBER = 10;
    private float receiverLatitude_;
    /**
     * <code>float receiverLatitude = 10;</code>
     */
    public float getReceiverLatitude() {
      return receiverLatitude_;
    }

    public static final int RECEIVERLONGITUDE_FIELD_NUMBER = 11;
    private float receiverLongitude_;
    /**
     * <code>float receiverLongitude = 11;</code>
     */
    public float getReceiverLongitude() {
      return receiverLongitude_;
    }

    public static final int RECEIVERNAME_FIELD_NUMBER = 12;
    private volatile java.lang.Object receiverName_;
    /**
     * <code>string receiverName = 12;</code>
     */
    public java.lang.String getReceiverName() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverName_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverNameBytes() {
      java.lang.Object ref = receiverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERPHONE_FIELD_NUMBER = 13;
    private volatile java.lang.Object receiverPhone_;
    /**
     * <code>string receiverPhone = 13;</code>
     */
    public java.lang.String getReceiverPhone() {
      java.lang.Object ref = receiverPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverPhone_ = s;
        return s;
      }
    }
    /**
     * <code>string receiverPhone = 13;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverPhoneBytes() {
      java.lang.Object ref = receiverPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOODSTYPE_FIELD_NUMBER = 14;
    private volatile java.lang.Object goodsType_;
    /**
     * <code>string goodsType = 14;</code>
     */
    public java.lang.String getGoodsType() {
      java.lang.Object ref = goodsType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        goodsType_ = s;
        return s;
      }
    }
    /**
     * <code>string goodsType = 14;</code>
     */
    public com.google.protobuf.ByteString
        getGoodsTypeBytes() {
      java.lang.Object ref = goodsType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goodsType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INCOME_FIELD_NUMBER = 15;
    private float income_;
    /**
     * <code>float income = 15;</code>
     */
    public float getIncome() {
      return income_;
    }

    public static final int DELIVERYFEE_FIELD_NUMBER = 16;
    private float deliveryFee_;
    /**
     * <code>float deliveryFee = 16;</code>
     */
    public float getDeliveryFee() {
      return deliveryFee_;
    }

    public static final int TIPFEE_FIELD_NUMBER = 17;
    private float tipFee_;
    /**
     * <code>float tipFee = 17;</code>
     */
    public float getTipFee() {
      return tipFee_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskNo_);
      }
      if (!getSenderAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderAddress_);
      }
      if (senderDistance_ != 0F) {
        output.writeFloat(3, senderDistance_);
      }
      if (senderLatitude_ != 0F) {
        output.writeFloat(4, senderLatitude_);
      }
      if (senderLongitude_ != 0F) {
        output.writeFloat(5, senderLongitude_);
      }
      if (!getSenderPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, senderPhone_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, senderName_);
      }
      if (!getReceiverAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, receiverAddress_);
      }
      if (receiverDistance_ != 0F) {
        output.writeFloat(9, receiverDistance_);
      }
      if (receiverLatitude_ != 0F) {
        output.writeFloat(10, receiverLatitude_);
      }
      if (receiverLongitude_ != 0F) {
        output.writeFloat(11, receiverLongitude_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, receiverName_);
      }
      if (!getReceiverPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, receiverPhone_);
      }
      if (!getGoodsTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, goodsType_);
      }
      if (income_ != 0F) {
        output.writeFloat(15, income_);
      }
      if (deliveryFee_ != 0F) {
        output.writeFloat(16, deliveryFee_);
      }
      if (tipFee_ != 0F) {
        output.writeFloat(17, tipFee_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskNo_);
      }
      if (!getSenderAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderAddress_);
      }
      if (senderDistance_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, senderDistance_);
      }
      if (senderLatitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, senderLatitude_);
      }
      if (senderLongitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, senderLongitude_);
      }
      if (!getSenderPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, senderPhone_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, senderName_);
      }
      if (!getReceiverAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, receiverAddress_);
      }
      if (receiverDistance_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, receiverDistance_);
      }
      if (receiverLatitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, receiverLatitude_);
      }
      if (receiverLongitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, receiverLongitude_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, receiverName_);
      }
      if (!getReceiverPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, receiverPhone_);
      }
      if (!getGoodsTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, goodsType_);
      }
      if (income_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(15, income_);
      }
      if (deliveryFee_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, deliveryFee_);
      }
      if (tipFee_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(17, tipFee_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail)) {
        return super.equals(obj);
      }
      com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail other = (com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail) obj;

      boolean result = true;
      result = result && getTaskNo()
          .equals(other.getTaskNo());
      result = result && getSenderAddress()
          .equals(other.getSenderAddress());
      result = result && (
          java.lang.Float.floatToIntBits(getSenderDistance())
          == java.lang.Float.floatToIntBits(
              other.getSenderDistance()));
      result = result && (
          java.lang.Float.floatToIntBits(getSenderLatitude())
          == java.lang.Float.floatToIntBits(
              other.getSenderLatitude()));
      result = result && (
          java.lang.Float.floatToIntBits(getSenderLongitude())
          == java.lang.Float.floatToIntBits(
              other.getSenderLongitude()));
      result = result && getSenderPhone()
          .equals(other.getSenderPhone());
      result = result && getSenderName()
          .equals(other.getSenderName());
      result = result && getReceiverAddress()
          .equals(other.getReceiverAddress());
      result = result && (
          java.lang.Float.floatToIntBits(getReceiverDistance())
          == java.lang.Float.floatToIntBits(
              other.getReceiverDistance()));
      result = result && (
          java.lang.Float.floatToIntBits(getReceiverLatitude())
          == java.lang.Float.floatToIntBits(
              other.getReceiverLatitude()));
      result = result && (
          java.lang.Float.floatToIntBits(getReceiverLongitude())
          == java.lang.Float.floatToIntBits(
              other.getReceiverLongitude()));
      result = result && getReceiverName()
          .equals(other.getReceiverName());
      result = result && getReceiverPhone()
          .equals(other.getReceiverPhone());
      result = result && getGoodsType()
          .equals(other.getGoodsType());
      result = result && (
          java.lang.Float.floatToIntBits(getIncome())
          == java.lang.Float.floatToIntBits(
              other.getIncome()));
      result = result && (
          java.lang.Float.floatToIntBits(getDeliveryFee())
          == java.lang.Float.floatToIntBits(
              other.getDeliveryFee()));
      result = result && (
          java.lang.Float.floatToIntBits(getTipFee())
          == java.lang.Float.floatToIntBits(
              other.getTipFee()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKNO_FIELD_NUMBER;
      hash = (53 * hash) + getTaskNo().hashCode();
      hash = (37 * hash) + SENDERADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getSenderAddress().hashCode();
      hash = (37 * hash) + SENDERDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSenderDistance());
      hash = (37 * hash) + SENDERLATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSenderLatitude());
      hash = (37 * hash) + SENDERLONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSenderLongitude());
      hash = (37 * hash) + SENDERPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getSenderPhone().hashCode();
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + RECEIVERADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverAddress().hashCode();
      hash = (37 * hash) + RECEIVERDISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getReceiverDistance());
      hash = (37 * hash) + RECEIVERLATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getReceiverLatitude());
      hash = (37 * hash) + RECEIVERLONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getReceiverLongitude());
      hash = (37 * hash) + RECEIVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverName().hashCode();
      hash = (37 * hash) + RECEIVERPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverPhone().hashCode();
      hash = (37 * hash) + GOODSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getGoodsType().hashCode();
      hash = (37 * hash) + INCOME_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getIncome());
      hash = (37 * hash) + DELIVERYFEE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDeliveryFee());
      hash = (37 * hash) + TIPFEE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTipFee());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseTaskDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseTaskDetail)
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.internal_static_ResponseTaskDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.internal_static_ResponseTaskDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail.class, com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail.Builder.class);
      }

      // Construct using com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskNo_ = "";

        senderAddress_ = "";

        senderDistance_ = 0F;

        senderLatitude_ = 0F;

        senderLongitude_ = 0F;

        senderPhone_ = "";

        senderName_ = "";

        receiverAddress_ = "";

        receiverDistance_ = 0F;

        receiverLatitude_ = 0F;

        receiverLongitude_ = 0F;

        receiverName_ = "";

        receiverPhone_ = "";

        goodsType_ = "";

        income_ = 0F;

        deliveryFee_ = 0F;

        tipFee_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.internal_static_ResponseTaskDetail_descriptor;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail getDefaultInstanceForType() {
        return com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail.getDefaultInstance();
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail build() {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail buildPartial() {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail result = new com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail(this);
        result.taskNo_ = taskNo_;
        result.senderAddress_ = senderAddress_;
        result.senderDistance_ = senderDistance_;
        result.senderLatitude_ = senderLatitude_;
        result.senderLongitude_ = senderLongitude_;
        result.senderPhone_ = senderPhone_;
        result.senderName_ = senderName_;
        result.receiverAddress_ = receiverAddress_;
        result.receiverDistance_ = receiverDistance_;
        result.receiverLatitude_ = receiverLatitude_;
        result.receiverLongitude_ = receiverLongitude_;
        result.receiverName_ = receiverName_;
        result.receiverPhone_ = receiverPhone_;
        result.goodsType_ = goodsType_;
        result.income_ = income_;
        result.deliveryFee_ = deliveryFee_;
        result.tipFee_ = tipFee_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail) {
          return mergeFrom((com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail other) {
        if (other == com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail.getDefaultInstance()) return this;
        if (!other.getTaskNo().isEmpty()) {
          taskNo_ = other.taskNo_;
          onChanged();
        }
        if (!other.getSenderAddress().isEmpty()) {
          senderAddress_ = other.senderAddress_;
          onChanged();
        }
        if (other.getSenderDistance() != 0F) {
          setSenderDistance(other.getSenderDistance());
        }
        if (other.getSenderLatitude() != 0F) {
          setSenderLatitude(other.getSenderLatitude());
        }
        if (other.getSenderLongitude() != 0F) {
          setSenderLongitude(other.getSenderLongitude());
        }
        if (!other.getSenderPhone().isEmpty()) {
          senderPhone_ = other.senderPhone_;
          onChanged();
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getReceiverAddress().isEmpty()) {
          receiverAddress_ = other.receiverAddress_;
          onChanged();
        }
        if (other.getReceiverDistance() != 0F) {
          setReceiverDistance(other.getReceiverDistance());
        }
        if (other.getReceiverLatitude() != 0F) {
          setReceiverLatitude(other.getReceiverLatitude());
        }
        if (other.getReceiverLongitude() != 0F) {
          setReceiverLongitude(other.getReceiverLongitude());
        }
        if (!other.getReceiverName().isEmpty()) {
          receiverName_ = other.receiverName_;
          onChanged();
        }
        if (!other.getReceiverPhone().isEmpty()) {
          receiverPhone_ = other.receiverPhone_;
          onChanged();
        }
        if (!other.getGoodsType().isEmpty()) {
          goodsType_ = other.goodsType_;
          onChanged();
        }
        if (other.getIncome() != 0F) {
          setIncome(other.getIncome());
        }
        if (other.getDeliveryFee() != 0F) {
          setDeliveryFee(other.getDeliveryFee());
        }
        if (other.getTipFee() != 0F) {
          setTipFee(other.getTipFee());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object taskNo_ = "";
      /**
       * <code>string taskNo = 1;</code>
       */
      public java.lang.String getTaskNo() {
        java.lang.Object ref = taskNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskNoBytes() {
        java.lang.Object ref = taskNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public Builder setTaskNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public Builder clearTaskNo() {
        
        taskNo_ = getDefaultInstance().getTaskNo();
        onChanged();
        return this;
      }
      /**
       * <code>string taskNo = 1;</code>
       */
      public Builder setTaskNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderAddress_ = "";
      /**
       * <code>string senderAddress = 2;</code>
       */
      public java.lang.String getSenderAddress() {
        java.lang.Object ref = senderAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderAddressBytes() {
        java.lang.Object ref = senderAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public Builder setSenderAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public Builder clearSenderAddress() {
        
        senderAddress_ = getDefaultInstance().getSenderAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string senderAddress = 2;</code>
       */
      public Builder setSenderAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderAddress_ = value;
        onChanged();
        return this;
      }

      private float senderDistance_ ;
      /**
       * <code>float senderDistance = 3;</code>
       */
      public float getSenderDistance() {
        return senderDistance_;
      }
      /**
       * <code>float senderDistance = 3;</code>
       */
      public Builder setSenderDistance(float value) {
        
        senderDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float senderDistance = 3;</code>
       */
      public Builder clearSenderDistance() {
        
        senderDistance_ = 0F;
        onChanged();
        return this;
      }

      private float senderLatitude_ ;
      /**
       * <code>float senderLatitude = 4;</code>
       */
      public float getSenderLatitude() {
        return senderLatitude_;
      }
      /**
       * <code>float senderLatitude = 4;</code>
       */
      public Builder setSenderLatitude(float value) {
        
        senderLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float senderLatitude = 4;</code>
       */
      public Builder clearSenderLatitude() {
        
        senderLatitude_ = 0F;
        onChanged();
        return this;
      }

      private float senderLongitude_ ;
      /**
       * <code>float senderLongitude = 5;</code>
       */
      public float getSenderLongitude() {
        return senderLongitude_;
      }
      /**
       * <code>float senderLongitude = 5;</code>
       */
      public Builder setSenderLongitude(float value) {
        
        senderLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float senderLongitude = 5;</code>
       */
      public Builder clearSenderLongitude() {
        
        senderLongitude_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object senderPhone_ = "";
      /**
       * <code>string senderPhone = 6;</code>
       */
      public java.lang.String getSenderPhone() {
        java.lang.Object ref = senderPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderPhone = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSenderPhoneBytes() {
        java.lang.Object ref = senderPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderPhone = 6;</code>
       */
      public Builder setSenderPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderPhone = 6;</code>
       */
      public Builder clearSenderPhone() {
        
        senderPhone_ = getDefaultInstance().getSenderPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string senderPhone = 6;</code>
       */
      public Builder setSenderPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderPhone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>string senderName = 7;</code>
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>string senderName = 7;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverAddress_ = "";
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public java.lang.String getReceiverAddress() {
        java.lang.Object ref = receiverAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverAddressBytes() {
        java.lang.Object ref = receiverAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public Builder setReceiverAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public Builder clearReceiverAddress() {
        
        receiverAddress_ = getDefaultInstance().getReceiverAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverAddress = 8;</code>
       */
      public Builder setReceiverAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverAddress_ = value;
        onChanged();
        return this;
      }

      private float receiverDistance_ ;
      /**
       * <code>float receiverDistance = 9;</code>
       */
      public float getReceiverDistance() {
        return receiverDistance_;
      }
      /**
       * <code>float receiverDistance = 9;</code>
       */
      public Builder setReceiverDistance(float value) {
        
        receiverDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float receiverDistance = 9;</code>
       */
      public Builder clearReceiverDistance() {
        
        receiverDistance_ = 0F;
        onChanged();
        return this;
      }

      private float receiverLatitude_ ;
      /**
       * <code>float receiverLatitude = 10;</code>
       */
      public float getReceiverLatitude() {
        return receiverLatitude_;
      }
      /**
       * <code>float receiverLatitude = 10;</code>
       */
      public Builder setReceiverLatitude(float value) {
        
        receiverLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float receiverLatitude = 10;</code>
       */
      public Builder clearReceiverLatitude() {
        
        receiverLatitude_ = 0F;
        onChanged();
        return this;
      }

      private float receiverLongitude_ ;
      /**
       * <code>float receiverLongitude = 11;</code>
       */
      public float getReceiverLongitude() {
        return receiverLongitude_;
      }
      /**
       * <code>float receiverLongitude = 11;</code>
       */
      public Builder setReceiverLongitude(float value) {
        
        receiverLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float receiverLongitude = 11;</code>
       */
      public Builder clearReceiverLongitude() {
        
        receiverLongitude_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object receiverName_ = "";
      /**
       * <code>string receiverName = 12;</code>
       */
      public java.lang.String getReceiverName() {
        java.lang.Object ref = receiverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverNameBytes() {
        java.lang.Object ref = receiverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public Builder setReceiverName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public Builder clearReceiverName() {
        
        receiverName_ = getDefaultInstance().getReceiverName();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverName = 12;</code>
       */
      public Builder setReceiverNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiverPhone_ = "";
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public java.lang.String getReceiverPhone() {
        java.lang.Object ref = receiverPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiverPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverPhoneBytes() {
        java.lang.Object ref = receiverPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiverPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public Builder setReceiverPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public Builder clearReceiverPhone() {
        
        receiverPhone_ = getDefaultInstance().getReceiverPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string receiverPhone = 13;</code>
       */
      public Builder setReceiverPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverPhone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object goodsType_ = "";
      /**
       * <code>string goodsType = 14;</code>
       */
      public java.lang.String getGoodsType() {
        java.lang.Object ref = goodsType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          goodsType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string goodsType = 14;</code>
       */
      public com.google.protobuf.ByteString
          getGoodsTypeBytes() {
        java.lang.Object ref = goodsType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          goodsType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string goodsType = 14;</code>
       */
      public Builder setGoodsType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        goodsType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string goodsType = 14;</code>
       */
      public Builder clearGoodsType() {
        
        goodsType_ = getDefaultInstance().getGoodsType();
        onChanged();
        return this;
      }
      /**
       * <code>string goodsType = 14;</code>
       */
      public Builder setGoodsTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        goodsType_ = value;
        onChanged();
        return this;
      }

      private float income_ ;
      /**
       * <code>float income = 15;</code>
       */
      public float getIncome() {
        return income_;
      }
      /**
       * <code>float income = 15;</code>
       */
      public Builder setIncome(float value) {
        
        income_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float income = 15;</code>
       */
      public Builder clearIncome() {
        
        income_ = 0F;
        onChanged();
        return this;
      }

      private float deliveryFee_ ;
      /**
       * <code>float deliveryFee = 16;</code>
       */
      public float getDeliveryFee() {
        return deliveryFee_;
      }
      /**
       * <code>float deliveryFee = 16;</code>
       */
      public Builder setDeliveryFee(float value) {
        
        deliveryFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float deliveryFee = 16;</code>
       */
      public Builder clearDeliveryFee() {
        
        deliveryFee_ = 0F;
        onChanged();
        return this;
      }

      private float tipFee_ ;
      /**
       * <code>float tipFee = 17;</code>
       */
      public float getTipFee() {
        return tipFee_;
      }
      /**
       * <code>float tipFee = 17;</code>
       */
      public Builder setTipFee(float value) {
        
        tipFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float tipFee = 17;</code>
       */
      public Builder clearTipFee() {
        
        tipFee_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ResponseTaskDetail)
    }

    // @@protoc_insertion_point(class_scope:ResponseTaskDetail)
    private static final com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail();
    }

    public static com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseTaskDetail>
        PARSER = new com.google.protobuf.AbstractParser<ResponseTaskDetail>() {
      public ResponseTaskDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseTaskDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseTaskDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseTaskDetail> getParserForType() {
      return PARSER;
    }

    public com.xinguang.tubobo.msgprotocol.transfer.ResponseTaskDetailPB.ResponseTaskDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseTaskDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseTaskDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ResponseTaskDetail.proto\"\212\003\n\022ResponseT" +
      "askDetail\022\016\n\006taskNo\030\001 \001(\t\022\025\n\rsenderAddre" +
      "ss\030\002 \001(\t\022\026\n\016senderDistance\030\003 \001(\002\022\026\n\016send" +
      "erLatitude\030\004 \001(\002\022\027\n\017senderLongitude\030\005 \001(" +
      "\002\022\023\n\013senderPhone\030\006 \001(\t\022\022\n\nsenderName\030\007 \001" +
      "(\t\022\027\n\017receiverAddress\030\010 \001(\t\022\030\n\020receiverD" +
      "istance\030\t \001(\002\022\030\n\020receiverLatitude\030\n \001(\002\022" +
      "\031\n\021receiverLongitude\030\013 \001(\002\022\024\n\014receiverNa" +
      "me\030\014 \001(\t\022\025\n\rreceiverPhone\030\r \001(\t\022\021\n\tgoods" +
      "Type\030\016 \001(\t\022\016\n\006income\030\017 \001(\002\022\023\n\013deliveryFe",
      "e\030\020 \001(\002\022\016\n\006tipFee\030\021 \001(\002B@\n(com.xinguang." +
      "tubobo.msgprotocol.transferB\024ResponseTas" +
      "kDetailPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ResponseTaskDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseTaskDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseTaskDetail_descriptor,
        new java.lang.String[] { "TaskNo", "SenderAddress", "SenderDistance", "SenderLatitude", "SenderLongitude", "SenderPhone", "SenderName", "ReceiverAddress", "ReceiverDistance", "ReceiverLatitude", "ReceiverLongitude", "ReceiverName", "ReceiverPhone", "GoodsType", "Income", "DeliveryFee", "TipFee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
